### ISSUE TITLE
Pickr without the small box

### ISSUE THREAD

**Issue by ArduinoidIOT** [Simonwep/pickr#236]
Is it possible to have the color picker always shown without the tiny box that shows the color?

**Comment by Simonwep** [comment]
You could simply hide the button via.
```css
.pcr-button {display: none;}
```

and use `inline: true;` or `showAlways: true;` in the configuration :)
